### PR TITLE
Added namespace to Context

### PR DESCRIPTION
**Pull request by shnhrrsn**
Possible fix for https://github.com/kylef/Stencil/issues/58

### CODE REVIEW

**Comment by shnhrrsn** [comment]
@kylef any thoughts on this? I'd be happy to implement a different way if you have suggestions.  This bug is blocking me on another project so I'm eager to get it fixed and tagged.

**Comment by kylef** [comment]
This way works for me :+1:. Thanks for the pull request.

**Comment by shnhrrsn** [comment]
@kylef any chance we can get this tagged in a new release?

**Comment by kylef** [comment]
Sorry for delay, I wanted to get more into the release but never found time.

https://github.com/kylef/Stencil/releases/tag/0.6.0-beta.1

**Pull request merged**
