### PR TITLE
New extensions API

### PR DESCRIPTION
**Pull request by kylef**
This PR removes the original `Namespace` class and replaces it with extensions. This allows the registration of multiple extensions in an environment.

```swift
let ext = Extension()
ext.registerTag(...)

let environment = Environment(extensions: [ext])
try environment.renderTemplate(name: "example.html")
```

### CODE REVIEW

**Comment by AliSoftware** [comment]
\cc @djbe a glimpse at new upcoming changes to integrate to SwiftGen soon 😉

**Comment by djbe** [comment]
Yeah, I noticed the changelog for master... I tried a pod update pointing to it (for https://github.com/AliSoftware/SwiftGen/pull/213), and got a whole bunch of compile errors. :scream: Reverted and better leave it until later 😅

**Comment by kylef** [comment]
@djbe Ah, willing to help since I know what's changed. How was you building SwiftGen with Stencil from source? Stuck with these CocoaPods limitations:

```
[!] Unable to satisfy the following requirements:

- `Stencil (from `https://github.com/kylef/Stencil`)` required by `Podfile`
- `Stencil (from `https://github.com/kylef/Stencil`)` required by `Podfile`
- `Stencil (= 0.7.1)` required by `Podfile.lock`
- `Stencil (= 0.7.2)` required by `GenumKit (4.0.1)`

Specs satisfying the `Stencil (from `https://github.com/kylef/Stencil`), Stencil (= 0.7.1), Stencil (= 0.7.2)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by djbe** [comment]
That'd definitely be welcome!

Yeah, I had to modify both the Podfile and genumkit.podspec:
- Point podfile to master
- Point genumkit to `~> 0.7.0`

Which is only temp. needed until there's a release.

**Pull request merged**
